dataset: Amazon2014Electronics_550_MMRec
root: ../../data

embedding_dim: 64
num_layers: 3

epochs: 500
batch_size: 4096
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-7

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20

vfile: visual_modality.pkl
tfile: textual_modality.pkl

mod_kappa: 10
shift_alpha: 0.0
shift_beta: 0.55