root: ../../data
dataset: Amazon2014Baby_550_MMRec

embedding_dim: 64
num_layers: 3

lr: 1.e-3
weight_decay: 1.e-2
optimizer: adam
epochs: 500
batch_size: 2048

scaling_factor: 5.
alpha: 1.0
beta: 1.0
weight4mid: 0.

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20

vfile: visual_modality.pkl
tfile: textual_modality.pkl

mod_kappa: 5
shift_mu: 0.05
shift_delta: 0.85